---
- name: add nginx mainline ppa
  apt_repository: repo='ppa:nginx/development'

- name: install packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - nginx

- name: Copy nginx configuration
  template: src=default.conf dest=/etc/nginx/sites-enabled/default
  notify: restart nginx