---
- name: add php ppa
  apt_repository: repo='ppa:ondrej/php'

- name: install packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - zip
    - unzip
    - git
    - mcrypt
    - sqlite3
    - php7.0-cli
    - php7.0-curl
    - php7.0-fpm
    - php7.0-intl
    - php7.0-json
    - php7.0-mcrypt
    - php7.0-sqlite3
    - php7.0-zip
    - php7.0-bcmath
    - php7.0-mysql